<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventJournal.Data\EventJournal.Data.csproj" />
    <ProjectReference Include="..\EventJournal.DomainEntities\EventJournal.DomainEntities.csproj" />
  </ItemGroup>

</Project>
